apiVersion: apps/v1
kind: Deployment
metadata:
  name: halal-life-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: halal-life-backend
  template:
    metadata:
      labels:
        app: halal-life-backend
    spec:
      containers:
        - name: backend
          image: halal-life-backend:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: halal-life-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
